title: João Lucas Coito  
#logo: 
#description: "Data Analyst with 12 years of experience in data analysis, transformation, and visualization, bringing a unique perspective from a biology background. I excel in analytical rigor and critical thinking, uncovering meaningful insights from complex datasets and translating them into actionable information. My experience spans data pipeline development, data quality assurance, and business intelligence reporting."
#show_downloads: true
theme: jekyll-theme-minimal
